#!/usr/bin/env node
/**
 * Generates src/environments/environment.ts (dev) or environment.prod.ts
 * (prod) from environment variables, since Angular cannot read .env files
 * on its own.
 *
 * Variable source, in priority order:
 *   1. Real process environment variables (e.g. set in Render's dashboard
 *      under the service's "Environment" tab in Step 4 — these are NOT
 *      read from any file on Render, they're injected directly by Render).
 *   2. .env in this folder, loaded via dotenv (local development only —
 *      copy .env.example to .env and fill in real values). dotenv does
 *      NOT override a variable that already has a real value in
 *      process.env, so this never fights with case 1.
 *   3. A safe placeholder, if neither of the above provided a value — the
 *      build still succeeds so CI/local `npm install` never breaks, but a
 *      warning is printed so a missing value is obvious.
 *
 * Usage: node scripts/generate-env.js <development|production>
 * (invoked automatically by `npm start` / `npm run build` — see package.json)
 */
const fs = require('fs');
const path = require('path');

// Loads .env into process.env if present; safe to call even if the file is
// missing (dotenv just no-ops), and never overwrites a var Render already set.
require('dotenv').config({ path: path.join(__dirname, '..', '.env'), quiet: true });

const mode = process.argv[2];
if (mode !== 'development' && mode !== 'production') {
  console.error('Usage: node scripts/generate-env.js <development|production>');
  process.exit(1);
}

function readVar(name, placeholder) {
  const value = process.env[name];
  if (!value) {
    console.warn(
      `[generate-env] Cảnh báo: biến "${name}" chưa được thiết lập ` +
        `(không có trong .env lẫn process.env). Dùng giá trị placeholder tạm thời — ` +
        `ứng dụng sẽ KHÔNG hoạt động đúng cho đến khi bạn điền giá trị thật ` +
        `(local: sửa frontend/.env; Render: Settings > Environment).`
    );
    return placeholder;
  }
  return value;
}

const apiBaseUrl = readVar(
  'API_BASE_URL',
  mode === 'production' ? 'https://YOUR-BACKEND-SERVICE.onrender.com/api' : 'http://localhost:8080/api'
);
const googleClientId = readVar('GOOGLE_CLIENT_ID', 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com');

const isProduction = mode === 'production';
const fileName = isProduction ? 'environment.prod.ts' : 'environment.ts';
const outPath = path.join(__dirname, '..', 'src', 'environments', fileName);

const content = `// AUTO-GENERATED by scripts/generate-env.js — DO NOT EDIT DIRECTLY.
// Edit frontend/.env (local) or the Render service's Environment Variables
// (production) instead, then re-run \`npm start\` / \`npm run build\`.
export const environment = {
  production: ${isProduction},
  apiBaseUrl: '${apiBaseUrl}',
  googleClientId: '${googleClientId}',
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`[generate-env] Đã sinh ${path.relative(process.cwd(), outPath)} (mode: ${mode})`);
