// AUTO-GENERATED by scripts/generate-env.js — DO NOT EDIT DIRECTLY.
// Edit frontend/.env (local) or the Render service's Environment Variables
// (production) instead, then re-run `npm start` / `npm run build`.
export const environment = {
  production: true,
  apiBaseUrl: 'https://YOUR-BACKEND-SERVICE.onrender.com/api',
  googleClientId: 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com',
};
